### ISSUE TITLE
How can i use it in a pure javascript project? 

### ISSUE THREAD

**Issue by erfanpaslar** [jd1378/persian-to-pinglish#1]
Hi
I wanted to use it in a 'none' node project.
for example I have a .js file that I want to call "p2f" function in it and first I have to import it, I looked in files but I couldn't find that function.
which file should I import to .js file?

**Comment by jd1378** [comment]
Hi
I have not completed the project and it is not usable right now as I stated in Readme, however you can fork the project and continue development if you need it
I had some ideas to go to from current state, but it needs too much effort and time which I currently am not willing to spend on this project. I was doing this solely out of curiosity.
Also for using inside a non node environment you can either download the package from npm and use the file with `.min.js` ending from `dist/` folder in your project or using a link

Still, I highly recommend against using it, as it is not working properly

**Comment by jd1378** [comment]
sorry, it was late time, so I took another look at project, there is no longer a simple p2f function that you can use , because I was experimenting with detecting the highest probability for all possible hejas for a word

and if you want to get that `dist/persian-to-pinglish.min.js` file , you have to clone the project, build the project, and then use the js file from it
you can do it like this:
```
git clone https://github.com/jd1378/persian-to-pinglish.git
cd persian-to-pinglish
yarn install # or 'npm install'
yarn build # or 'npm run build'
```
the mentioned file will be built. but node.js should be already installed on your system. but after the build its not needed anymore.

**Comment by jd1378** [comment]
@erfanpaslar 
I cleaned up some parts of the project and published a new version that makes the current work-in-progress methods usable. (the state of project was not much clear before)

**Comment by jd1378** [comment]
there was an issue with the publish I did today, please use 0.4.4 if you will.

**Comment by jd1378** [comment]
I will open this issue till I do some tests and make sure it is usable in browser environment as well.

**Comment by jd1378** [comment]
My rollup settings had problem. Sorry. It's fixed now and I have also made a demo that you can check out from here: https://jd1378.github.io/persian-to-pinglish/

and again, It's pretty much unusable right now I believe.

You have to use the `persian-to-pinglish.umd.js` if you want to use it in your project.
